# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181116_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='Modifiedat',
        ),
    ]
