# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_todolist_modifiedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='Modifiedat',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
