# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 05:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Order_id',
            new_name='order_id',
        ),
    ]
