# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Apl', '0002_auto_20180731_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.CharField(max_length=250)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apl.Customer')),
            ],
        ),
    ]
