# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-22 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apl', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('addr', models.CharField(max_length=220)),
            ],
        ),
    ]
