# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-20 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='catagery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.Catagery'),
            preserve_default=False,
        ),
    ]
