# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-20 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_cake_catagery'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
