# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='abc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=225)),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
