# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-14 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20190214_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='gift',
            field=models.ManyToManyField(to='product.Gift'),
        ),
    ]
