# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-14 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_cart_gift'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Cake')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Gift')),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cake',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='gift',
        ),
        migrations.AddField(
            model_name='cart',
            name='Catagery',
            field=models.ManyToManyField(to='product.Catagery'),
        ),
    ]
