# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-14 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20190214_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Catagery',
        ),
        migrations.RemoveField(
            model_name='catagery',
            name='cake',
        ),
        migrations.RemoveField(
            model_name='catagery',
            name='gift',
        ),
        migrations.AddField(
            model_name='cake',
            name='catagery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.Catagery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catagery',
            name='name',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
    ]
