# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-14 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20190214_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(blank=True, max_length=225, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('message', models.CharField(blank=True, max_length=225, null=True)),
                ('catagery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Catagery')),
            ],
        ),
    ]
