# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-12 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Message',
        ),
        migrations.AddField(
            model_name='post',
            name='blood_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='APP.BloodGroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
    ]
