# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-17 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('phone', models.CharField(max_length=220)),
                ('email', models.EmailField(max_length=254)),
                ('add', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='table',
        ),
    ]
